# This is a basic workflow to help you get started with Actions

name: ci-build-workflow

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup python environment 
        uses: actions/setup-python@v5
        with:
           python-version: '3.x'
           
      - name: Install dependencies
        run: python -m pip install --upgrade pip
             pip install -r requirements.txt

      - name: build the docker image
        run: |
         cd examples/python-web-app
         docker build -t python-demo-app:v1 .
         docker tag python-demo-app:v1 smritidn6docker/python-demo-app:v1

      - name: Push the image to dokerhub
        run: |
         docker login --username smritidn6docker --password ${{ secrets.DOCKER_PASSWORD }}
         docker push frontend
